### ISSUE TITLE
Non workspace files show up in open panel

### ISSUE THREAD

**Issue by certainlyakey** [jmooney/EasyWorkspace-sublime#11]
Files that are not workspaces (most apparently system/hidden files) show up in the open panel. On my Mac for example a `.DS_Store` appeared: https://monosnap.com/direct/nctTfblz6fNT9g2Gltz8bXcQByp7gG. 

Such files should be hidden it seems and only files with `.ws` extension should be listed.

**Comment by jmooney** [comment]
Good suggestion! Will be included in next release.

**Comment by jmooney** [comment]
Merged into master.
